[build]
builder = "vite"

[deploy]
startCommand = "npm run preview"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[build.watchPatterns]
include = ["src/**", "public/**", "index.html", "vite.config.ts", "package.json"]